[project]
name = "__PROJECT_NAME__"
version = "0.1.0"
description = "MCP server"
requires-python = ">=3.9"
dependencies = [
  "mcp"
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
